//! CLDR JSON → `verbalize/src/data/*.rs`. Pure function of the vendored
//! files: `generate` returns `(file name, source)` pairs; the caller writes
//! or compares them.

use serde_json::{Map, Value};
use std::fmt::Write;
use std::fs;
use std::path::Path;

pub type Error = Box<dyn std::error::Error>;
pub type Result<T, E = Error> = std::result::Result<T, E>;

pub const LANGUAGES: [&str; 3] = ["de", "en", "ro"];
pub const SUPPLEMENTAL: &str = "cldr-core/supplemental/currencyData.json";

/// The per-language files of design spec §6.1, relative to `cldr-json/` in
/// the upstream repository and to `xtask/cldr/` locally.
pub fn lang_files(lang: &str) -> [String; 5] {
    [
        format!("cldr-rbnf/rbnf/{lang}.json"),
        format!("cldr-numbers-full/main/{lang}/numbers.json"),
        format!("cldr-numbers-full/main/{lang}/currencies.json"),
        format!("cldr-units-full/main/{lang}/units.json"),
        format!("cldr-dates-full/main/{lang}/ca-gregorian.json"),
    ]
}

pub fn generate(cldr: &Path, tag: &str) -> Result<Vec<(String, String)>> {
    let header = header(cldr, tag)?;
    let mut files = Vec::new();
    for lang in LANGUAGES {
        files.push((format!("{lang}.rs"), lang_source(cldr, lang, &header)?));
    }
    files.push((
        "supplemental.rs".to_string(),
        supplemental_source(cldr, &header)?,
    ));
    Ok(files)
}

fn header(cldr: &Path, tag: &str) -> Result<String> {
    let license =
        fs::read_to_string(cldr.join("LICENSE")).map_err(|e| format!("xtask/cldr/LICENSE: {e}"))?;
    let copyright = license
        .lines()
        .find(|l| l.starts_with("Copyright ©"))
        .ok_or("xtask/cldr/LICENSE: no copyright line")?;
    Ok(format!(
        "// Data from Unicode CLDR, vendored from unicode-org/cldr-json at tag {tag}.\n\
         // {copyright}\n\
         // Used under the Unicode License v3 (SPDX-License-Identifier: Unicode-3.0);\n\
         // the copyright and permission notice is in NOTICE at the repository root.\n\
         // generated by cargo xtask gen from cldr-json {tag}; do not edit\n\n"
    ))
}

// ---------------------------------------------------------------- language

fn lang_source(cldr: &Path, lang: &str, header: &str) -> Result<String> {
    let [rbnf, numbers, currencies, units, dates] = lang_files(lang);
    let rbnf = Json::load(cldr, &rbnf)?;
    let numbers = Json::load(cldr, &numbers)?;
    let currencies = Json::load(cldr, &currencies)?;
    let units = Json::load(cldr, &units)?;
    let dates = Json::load(cldr, &dates)?;

    let symbols = symbols(&numbers, lang)?;
    let rulesets = rulesets(&rbnf, lang)?;
    check_rbnf(lang, &symbols, &rulesets).map_err(|e| format!("{}: {e}", rbnf.file))?;

    let mut out = String::from(header);
    out.push_str("use super::*;\n\n#[rustfmt::skip]\n");
    writeln!(
        out,
        "pub static {}: LangData = LangData {{",
        lang.to_uppercase()
    )?;
    writeln!(out, "    language: {},", lit(lang))?;
    write_symbols(&mut out, &symbols)?;
    write_rbnf(&mut out, &rulesets)?;
    write_currencies(&mut out, &currencies, lang)?;
    out.push_str("    currency_digits: supplemental::CURRENCY_DIGITS,\n");
    out.push_str("    currency_digits_default: supplemental::CURRENCY_DIGITS_DEFAULT,\n");
    write_units(&mut out, &units, lang)?;
    write_calendar(&mut out, &dates, lang)?;
    out.push_str("};\n");
    Ok(out)
}

/// `NumberSymbols` field name and value, in struct order.
type Symbols = [(&'static str, String); 5];

fn symbols(json: &Json, lang: &str) -> Result<Symbols> {
    let numbers = format!("main/{lang}/numbers");
    let system = json.string(&format!("{numbers}/defaultNumberingSystem"))?;
    if system != "latn" {
        return Err(format!(
            "{}: default numbering system is {system}, not latn",
            json.file
        )
        .into());
    }
    let symbols = format!("{numbers}/symbols-numberSystem-latn");
    let get = |key: &str| json.string(&format!("{symbols}/{key}")).map(str::to_string);
    Ok([
        ("decimal", get("decimal")?),
        ("group", get("group")?),
        ("percent", get("percentSign")?),
        ("permille", get("perMille")?),
        ("minus", get("minusSign")?),
    ])
}

fn write_symbols(out: &mut String, symbols: &Symbols) -> Result<()> {
    out.push_str("    symbols: NumberSymbols {\n");
    for (field, value) in symbols {
        writeln!(out, "        {field}: {},", lit(value))?;
    }
    out.push_str("    },\n");
    Ok(())
}

/// `(name, [(descriptor, body)])` for every `SpelloutRules` ruleset, in file order.
type Rulesets = Vec<(String, Vec<(String, String)>)>;

fn rulesets(json: &Json, lang: &str) -> Result<Rulesets> {
    let identity = json.string("rbnf/identity/language")?;
    if identity != lang {
        return Err(format!("{}: identity is {identity}, expected {lang}", json.file).into());
    }
    let mut rulesets = Vec::new();
    for (name, rules) in json.object("rbnf/rbnf/SpelloutRules")? {
        if name.starts_with('_') {
            continue; // `_rbnfRulesFile` metadata
        }
        let ctx = format!("{}: SpelloutRules/{name}", json.file);
        let mut pairs = Vec::new();
        for rule in rules
            .as_array()
            .ok_or_else(|| format!("{ctx}: not an array"))?
        {
            let pair = rule.as_array().filter(|p| p.len() == 2);
            let (descriptor, body) = match pair.map(|p| (p[0].as_str(), p[1].as_str())) {
                Some((Some(d), Some(b))) => (d, b),
                _ => return Err(format!("{ctx}: rule is not [descriptor, body]: {rule}").into()),
            };
            pairs.push((descriptor.to_string(), body.to_string()));
        }
        rulesets.push((name.clone(), pairs));
    }
    Ok(rulesets)
}

/// Runs the library's RBNF parser over the rules before they are written,
/// so syntax outside its scope fails here with the rule quoted (design §8).
fn check_rbnf(lang: &str, symbols: &Symbols, rulesets: &Rulesets) -> Result<()> {
    let rules: Vec<Vec<(&str, &str)>> = rulesets
        .iter()
        .map(|(_, rules)| {
            rules
                .iter()
                .map(|(d, b)| (d.as_str(), b.as_str()))
                .collect()
        })
        .collect();
    let refs: Vec<(&str, &[(&str, &str)])> = rulesets
        .iter()
        .zip(&rules)
        .map(|((name, _), rules)| (name.as_str(), rules.as_slice()))
        .collect();
    let [decimal, group, _, _, minus] = symbols;
    verbalize::check_rbnf(lang, [&decimal.1, &group.1, &minus.1], &refs)?;
    Ok(())
}

fn write_rbnf(out: &mut String, rulesets: &Rulesets) -> Result<()> {
    out.push_str("    rbnf: &[\n");
    for (name, rules) in rulesets {
        writeln!(out, "        Ruleset {{ name: {}, rules: &[", lit(name))?;
        for (descriptor, body) in rules {
            writeln!(out, "            ({}, {}),", lit(descriptor), lit(body))?;
        }
        out.push_str("        ] },\n");
    }
    out.push_str("    ],\n");
    Ok(())
}

fn write_currencies(out: &mut String, json: &Json, lang: &str) -> Result<()> {
    out.push_str("    currencies: &[\n");
    for (code, entry) in json.object(&format!("main/{lang}/numbers/currencies"))? {
        let ctx = format!("{}: {code}", json.file);
        let mut name = None;
        let mut names = Vec::new();
        let (mut symbol, mut narrow, mut variant) = (None, None, None);
        for (key, value) in expect_object(entry, &ctx)? {
            let value = expect_str(value, &format!("{ctx}/{key}"))?;
            match key.as_str() {
                "displayName" => name = Some(value),
                "symbol" => symbol = Some(value),
                "symbol-alt-narrow" => narrow = Some(value),
                "symbol-alt-variant" => variant = Some(value),
                _ => match key.strip_prefix("displayName-count-") {
                    Some(plural) => names.push((plural_variant(plural, &ctx)?, value)),
                    None => return Err(format!("{ctx}: unknown key {key}").into()),
                },
            }
        }
        let name = name.ok_or_else(|| format!("{ctx}: no displayName"))?;
        let names: Vec<String> = names
            .iter()
            .map(|(plural, value)| format!("(PluralCategory::{plural}, {})", lit(value)))
            .collect();
        writeln!(
            out,
            "        Currency {{ code: {}, name: {}, names: &[{}], symbol: {}, symbol_narrow: {}, symbol_variant: {} }},",
            lit(code),
            lit(name),
            names.join(", "),
            opt_lit(symbol),
            opt_lit(narrow),
            opt_lit(variant)
        )?;
    }
    out.push_str("    ],\n");
    Ok(())
}

/// Unit ids look like `length-kilometer`; the rest of the `long`/`short`
/// maps are prefixes (`10p3`, `1024p2`) and compound patterns (`per`,
/// `power2`, `coordinateUnit`).
fn is_unit(id: &str) -> bool {
    id.contains('-') && !id.starts_with("10p") && !id.starts_with("1024p")
}

struct UnitForms<'a> {
    gender: Option<&'a str>,
    name: Option<&'a str>,
    per: Option<&'a str>,
    /// `(plural, case, pattern)` in CLDR order.
    patterns: Vec<(&'static str, &'static str, &'a str)>,
}

/// Forms of one unit in one width; empty when the width lacks the unit.
fn unit_forms<'a>(entry: Option<&'a Value>, ctx: &str) -> Result<UnitForms<'a>> {
    let mut forms = UnitForms {
        gender: None,
        name: None,
        per: None,
        patterns: Vec::new(),
    };
    let Some(entry) = entry else { return Ok(forms) };
    for (key, value) in expect_object(entry, ctx)? {
        let value = expect_str(value, &format!("{ctx}/{key}"))?;
        match key.as_str() {
            "gender" => forms.gender = Some(value),
            "displayName" => forms.name = Some(value),
            "perUnitPattern" => forms.per = Some(value),
            _ => match key.split_once("-count-") {
                Some((form, plural)) => {
                    let case = if form == "unitPattern" {
                        "Nominative"
                    } else {
                        case_variant(form, ctx)?
                    };
                    forms
                        .patterns
                        .push((plural_variant(plural, ctx)?, case, value));
                }
                None => return Err(format!("{ctx}: unknown key {key}").into()),
            },
        }
    }
    Ok(forms)
}

fn write_units(out: &mut String, json: &Json, lang: &str) -> Result<()> {
    let long = json.object(&format!("main/{lang}/units/long"))?;
    let short = json.object(&format!("main/{lang}/units/short"))?;
    let ids = long.keys().filter(|id| is_unit(id)).chain(
        short
            .keys()
            .filter(|id| is_unit(id) && !long.contains_key(*id)),
    );
    out.push_str("    units: &[\n");
    for id in ids {
        let l = unit_forms(long.get(id), &format!("{}: long/{id}", json.file))?;
        let s = unit_forms(short.get(id), &format!("{}: short/{id}", json.file))?;
        let gender = match l.gender {
            Some(g) => format!("Some(Gender::{})", gender_variant(g, id)?),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "        Unit {{ id: {}, gender: {gender}, long_name: {}, long_per: {}, long: &[",
            lit(id),
            opt_lit(l.name),
            opt_lit(l.per)
        )?;
        write_patterns(out, &l.patterns)?;
        writeln!(out, "        ], short_name: {}, short: &[", opt_lit(s.name))?;
        write_patterns(out, &s.patterns)?;
        out.push_str("        ] },\n");
    }
    out.push_str("    ],\n");
    write_prefixes(out, long, &json.file)?;
    Ok(())
}

/// `10p3: Kilo{0}`, `10p-6: Mikro{0}`: SI prefix patterns, keyed by the
/// power of ten. Binary prefixes (`1024p…`) are not needed.
fn write_prefixes(out: &mut String, long: &Map<String, Value>, file: &str) -> Result<()> {
    out.push_str("    unit_prefixes: &[\n");
    for (id, entry) in long {
        let Some(power) = id.strip_prefix("10p") else {
            continue;
        };
        let power: i8 = power.parse().map_err(|e| format!("{file}: {id}: {e}"))?;
        let ctx = format!("{file}: long/{id}");
        let pattern = entry
            .get("unitPrefixPattern")
            .ok_or_else(|| format!("{ctx}: no unitPrefixPattern"))?;
        writeln!(
            out,
            "        ({power}, {}),",
            lit(expect_str(pattern, &ctx)?)
        )?;
    }
    out.push_str("    ],\n");
    Ok(())
}

fn write_patterns(out: &mut String, patterns: &[(&str, &str, &str)]) -> Result<()> {
    for (plural, case, pattern) in patterns {
        writeln!(
            out,
            "            UnitPattern {{ plural: PluralCategory::{plural}, case: Case::{case}, pattern: {} }},",
            lit(pattern)
        )?;
    }
    Ok(())
}

fn write_calendar(out: &mut String, json: &Json, lang: &str) -> Result<()> {
    let gregorian = format!("main/{lang}/dates/calendars/gregorian");
    let months: Vec<String> = (1..=12).map(|m| m.to_string()).collect();
    let days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
    for (field, path, keys) in [
        (
            "months_wide",
            "months/format/wide",
            months.iter().map(String::as_str).collect::<Vec<_>>(),
        ),
        (
            "months_abbreviated",
            "months/format/abbreviated",
            months.iter().map(String::as_str).collect(),
        ),
        ("weekdays_wide", "days/format/wide", days.to_vec()),
        (
            "weekdays_abbreviated",
            "days/format/abbreviated",
            days.to_vec(),
        ),
    ] {
        let names = keys
            .iter()
            .map(|key| json.string(&format!("{gregorian}/{path}/{key}")).map(lit))
            .collect::<Result<Vec<_>>>()?;
        writeln!(out, "    {field}: [{}],", names.join(", "))?;
    }
    Ok(())
}

// ------------------------------------------------------------ supplemental

fn supplemental_source(cldr: &Path, header: &str) -> Result<String> {
    let json = Json::load(cldr, SUPPLEMENTAL)?;
    let mut rows = Vec::new();
    let mut default = None;
    for (code, entry) in json.object("supplemental/currencyData/fractions")? {
        let ctx = format!("{}: fractions/{code}", json.file);
        let digits = entry
            .get("_digits")
            .ok_or_else(|| format!("{ctx}: no _digits"))?;
        let digits: u8 = expect_str(digits, &ctx)?
            .parse()
            .map_err(|e| format!("{ctx}: _digits: {e}"))?;
        if code == "DEFAULT" {
            default = Some(digits);
        } else {
            rows.push((code.as_str(), digits));
        }
    }
    let default = default.ok_or_else(|| format!("{}: no DEFAULT fraction", json.file))?;
    rows.sort();

    let mut out = String::from(header);
    out.push_str(
        "/// Minor-unit digits by ISO 4217 code, ascending (supplemental `currencyData`).\n",
    );
    out.push_str("#[rustfmt::skip]\npub const CURRENCY_DIGITS: &[(&str, u8)] = &[\n");
    for (code, digits) in rows {
        writeln!(out, "    ({}, {digits}),", lit(code))?;
    }
    out.push_str("];\n\n");
    out.push_str("/// Digits for codes not listed in `CURRENCY_DIGITS`.\n");
    writeln!(out, "pub const CURRENCY_DIGITS_DEFAULT: u8 = {default};")?;
    Ok(out)
}

// ----------------------------------------------------------------- helpers

struct Json {
    file: String,
    value: Value,
}

impl Json {
    fn load(cldr: &Path, rel: &str) -> Result<Json> {
        let text = fs::read_to_string(cldr.join(rel))
            .map_err(|e| format!("xtask/cldr/{rel}: {e}; run `cargo xtask cldr-update <tag>`"))?;
        let value = serde_json::from_str(&text).map_err(|e| format!("{rel}: {e}"))?;
        Ok(Json {
            file: rel.to_string(),
            value,
        })
    }

    /// `path` is `/`-separated object keys.
    fn at(&self, path: &str) -> Result<&Value> {
        let mut v = &self.value;
        for key in path.split('/') {
            v = v
                .get(key)
                .ok_or_else(|| format!("{}: missing {path}", self.file))?;
        }
        Ok(v)
    }

    fn string(&self, path: &str) -> Result<&str> {
        expect_str(self.at(path)?, &format!("{}: {path}", self.file))
    }

    fn object(&self, path: &str) -> Result<&Map<String, Value>> {
        expect_object(self.at(path)?, &format!("{}: {path}", self.file))
    }
}

fn expect_str<'a>(v: &'a Value, ctx: &str) -> Result<&'a str> {
    v.as_str()
        .ok_or_else(|| format!("{ctx}: not a string: {v}").into())
}

fn expect_object<'a>(v: &'a Value, ctx: &str) -> Result<&'a Map<String, Value>> {
    v.as_object()
        .ok_or_else(|| format!("{ctx}: not an object").into())
}

fn plural_variant(plural: &str, ctx: &str) -> Result<&'static str> {
    Ok(match plural {
        "zero" => "Zero",
        "one" => "One",
        "two" => "Two",
        "few" => "Few",
        "many" => "Many",
        "other" => "Other",
        _ => return Err(format!("{ctx}: unknown plural category {plural}").into()),
    })
}

fn case_variant(case: &str, ctx: &str) -> Result<&'static str> {
    Ok(match case {
        "accusative" => "Accusative",
        "dative" => "Dative",
        "genitive" => "Genitive",
        _ => {
            return Err(
                format!("{ctx}: unknown case {case}; add it to verbalize::token::Case").into(),
            )
        }
    })
}

fn gender_variant(gender: &str, ctx: &str) -> Result<&'static str> {
    Ok(match gender {
        "masculine" => "Masculine",
        "feminine" => "Feminine",
        "neuter" => "Neuter",
        _ => {
            return Err(format!(
                "{ctx}: unknown gender {gender}; add it to verbalize::token::Gender"
            )
            .into())
        }
    })
}

/// Rust string literal. Non-ASCII letters and symbols stay readable
/// (`zwölf`, `→→`); invisible characters that editors would mangle are
/// escaped (soft hyphen, narrow no-break space, zero-width joiners).
fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            ' ' => out.push(' '),
            c if c.is_control() || c.is_whitespace() => escape(&mut out, c),
            '\u{ad}' | '\u{200b}'..='\u{200f}' | '\u{2060}' | '\u{feff}' => escape(&mut out, c),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn escape(out: &mut String, c: char) {
    write!(out, "\\u{{{:x}}}", c as u32).unwrap();
}

fn opt_lit(s: Option<&str>) -> String {
    match s {
        Some(s) => format!("Some({})", lit(s)),
        None => "None".to_string(),
    }
}
